version: '3'
services:
  server:
    image: node:10
    container_name: server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8003
      - TS_NODE_FILES=true
    working_dir: /usr/src/app
    command: bash -c "yarn install && yarn build && yarn start"
    ports:
      - '8003:8003'
